### ISSUE TITLE
error when open kicad file in R4 folder

### ISSUE THREAD

**Issue by kawashimaken** [imliubo/M5Pi#2]
Thank you for sharing this great project!

An error occurred when opening the KiCad file in the R4 folder.
The KiCad file in R3 folder had no problem.
I am using KiCad 6.01 (6.05 shows the same error), should I switch to KiCad 5? or Do I have to use a specific version of KiCad?
Thank you!

**Comment by imliubo** [comment]
Sorry,I must not have mentioned, I am using kicad-nightly, please try again with the kicad-nighly version.

**Comment by kawashimaken** [comment]
Thank you!
I will try kicad-nighly next!
