### ISSUE TITLE
M5Pi-Launcher中的库缺少CMakeList.txt，编译失败

### ISSUE THREAD

**Issue by xxzling** [imliubo/M5Pi#4]
您好，M5Pi-Launcher中的库缺少CMakeList.txt，例如lv_fs_if、nes等，导致编译失败，手动添加内容为file(GLOB SOURCES *.c)后又不能生成*.a文件，请问有什么解决方法吗？

**Comment by imliubo** [comment]
看一下 [M5Pi-Launcher](https://github.com/imliubo/M5Pi-Launcher/tree/870a251a8f5348b5696e45d8034bc286631881a7)中的 patch 文件夹和 顶层 CMakeList.tx
